import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { apiFetch } from "../lib/api";

const styles=["Adventure","Relaxed","Backpacking","Cultural","Luxury","Nature"];
const tags=["Hiking","Food","Photography","Beaches","Nightlife","Museums","Road trips","Camping"];

export default function CreateTrip(){
 const nav=useNavigate(); const [form,setForm]=useState({title:"",destination:"",start_date:"",end_date:"",budget_min:"",budget_max:"",currency:"INR",travel_style:"Adventure",interests:[],activities:[],description:"",status:"open"}); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 const set=(k,v)=>setForm(f=>({...f,[k]:v})); const toggle=(k,v)=>set(k,form[k].includes(v)?form[k].filter(x=>x!==v):[...form[k],v]);
 async function submit(e){e.preventDefault();setSaving(true);setError("");try{await apiFetch("/trips",{method:"POST",body:JSON.stringify({...form,budget_min:form.budget_min?Number(form.budget_min):null,budget_max:form.budget_max?Number(form.budget_max):null})});nav("/my-trips");}catch(err){setError(err.message)}finally{setSaving(false)}}
 return <div className="content-wrap"><div className="page-heading"><div><p className="eyebrow">PLAN A JOURNEY</p><h1>Create trip</h1><p>Give your journey enough detail for meaningful traveller matching.</p></div></div><form className="profile-card trip-form" onSubmit={submit}><div className="form-grid"><label>Trip title<input required value={form.title} onChange={e=>set("title",e.target.value)} placeholder="Weekend in Goa"/></label><label>Destination<input required value={form.destination} onChange={e=>set("destination",e.target.value)} placeholder="Goa, India"/></label><label>Start date<input required type="date" value={form.start_date} onChange={e=>set("start_date",e.target.value)}/></label><label>End date<input required type="date" value={form.end_date} onChange={e=>set("end_date",e.target.value)}/></label><label>Minimum budget<input type="number" min="0" value={form.budget_min} onChange={e=>set("budget_min",e.target.value)} placeholder="5000"/></label><label>Maximum budget<input type="number" min="0" value={form.budget_max} onChange={e=>set("budget_max",e.target.value)} placeholder="15000"/></label><label>Travel style<select value={form.travel_style} onChange={e=>set("travel_style",e.target.value)}>{styles.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={form.status} onChange={e=>set("status",e.target.value)}><option value="open">Open for matching</option><option value="draft">Save as draft</option></select></label><label className="full">Description<textarea rows="4" value={form.description} onChange={e=>set("description",e.target.value)} placeholder="What kind of trip are you planning?"/></label></div><div className="choice-section"><strong>Interests</strong><div className="choice-row">{tags.map(x=><button type="button" key={x} className={form.interests.includes(x)?"choice selected":"choice"} onClick={()=>toggle("interests",x)}>{x}</button>)}</div></div><div className="choice-section"><strong>Activities</strong><div className="choice-row">{tags.map(x=><button type="button" key={x} className={form.activities.includes(x)?"choice selected":"choice"} onClick={()=>toggle("activities",x)}>{x}</button>)}</div></div>{error&&<p className="form-error">{error}</p>}<div className="actions"><button className="button" disabled={saving}>{saving?"Creating…":"Create trip"}</button><button type="button" className="button button-light" onClick={()=>nav("/my-trips")}>Cancel</button></div></form></div>
}