import { useEffect,useState } from "react";
import { Link } from "react-router-dom";
import { apiFetch } from "../lib/api";

export default function ExploreTrips(){
 const [trips,setTrips]=useState([]),[sent,setSent]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{apiFetch("/explore/trips").then(r=>setTrips(r.trips||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 async function request(id){try{await apiFetch("/requests",{method:"POST",body:JSON.stringify({trip_id:id})});setSent(x=>({...x,[id]:true}))}catch(e){setError(e.message)}}
 return <div className="content-wrap"><div className="page-heading"><div><p className="eyebrow">EXPLORE TRIPS</p><h1>See where the community is going.</h1><p>Open trips from discoverable travellers are shown here so you can explore real plans before connecting.</p></div><Link className="button" to="/my-trips/new">Create trip →</Link></div>{error&&<p className="form-error">{error}</p>}{loading?<section className="empty-state-card"><h2>Loading community trips…</h2></section>:trips.length===0?<><section className="demo-banner"><strong>Demo preview</strong><span>These example trips are shown only because no public trips exist yet. They are not stored in the database.</span></section><div className="explore-trip-grid">{[["Goa, India","Weekend Beach Escape","Arjun","Bengaluru","Budget-friendly"],["Manali, India","Mountain Adventure","Priya","Chennai","Adventure"],["Kerala, India","Slow Travel & Food","Rahul","Hyderabad","Relaxed"]].map(([destination,title,name,city,style],i)=><article className="explore-trip-card" key={destination}><div className={"explore-trip-image demo-image demo-"+i}><span>DEMO</span></div><div className="explore-trip-body"><div className="explore-trip-user"><div className="mini-avatar">{name.slice(0,1)}</div><div><strong>{name}</strong><small>{city}</small></div></div><p className="eyebrow">{destination}</p><h2>{title}</h2><p>Example trip · dates shown after real trip creation</p><div className="trip-meta"><span>INR 10k–25k</span><span>{style}</span></div><div className="explore-actions"><button className="button button-light" disabled>Demo profile</button><button className="button" disabled>Demo request</button></div></div></article>)}</div></>:<div className="explore-trip-grid">{trips.map(t=><article className="explore-trip-card" key={t.id}><div className="explore-trip-image" style={t.profile?.avatar_url?{backgroundImage:"url("+t.profile.avatar_url+")"}:{}}><span>{t.status}</span></div><div className="explore-trip-body"><div className="explore-trip-user"><div className="mini-avatar">{(t.profile?.display_name||"T").slice(0,1)}</div><div><strong>{t.profile?.display_name||"Traveller"}</strong><small>{t.profile?.home_city||"Location private"}</small></div></div><p className="eyebrow">{t.destination}</p><h2>{t.title}</h2><p>{new Date(t.start_date).toLocaleDateString()} — {new Date(t.end_date).toLocaleDateString()}</p><div className="trip-meta"><span>{t.currency} {t.budget_min??"—"}–{t.budget_max??"—"}</span><span>{t.travel_style||"Any style"}</span></div><div className="explore-actions"><Link className="button button-light" to={"/traveller/"+t.user_id}>View traveller</Link><button className="button" disabled={sent[t.id]} onClick={()=>request(t.id)}>{sent[t.id]?"Request sent":"Send request"}</button></div></div></article>)}</div>}</div>}
