import { useEffect, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { getProfile, updateProfile, uploadProfilePhoto, uploadProfileImage } from "../lib/profile";
import { apiFetch } from "../lib/api";
import { supabase } from "../lib/supabase";
import { signOut } from "../lib/auth";

const travelStyles=["Backpacking","Relaxed","Adventure","Luxury","Budget-friendly","Road trip","Nature & outdoors"];
const interestOptions=["Mountains","Beaches","Food","Photography","Culture","Nature","History","Nightlife","Wildlife","Road trips"];
const activityOptions=["Trekking","Hiking","Camping","Sightseeing","Scuba diving","Cycling","Local food","Photography"];
function toggleItem(list,item){return list.includes(item)?list.filter(x=>x!==item):[...list,item]}

export default function Profile(){
 const {user}=useAuth(); const navigate=useNavigate(); const fileRef=useRef(null); const backgroundFileRef=useRef(null); const postFileRef=useRef(null);
 const [profile,setProfile]=useState(null),[form,setForm]=useState({}),[posts,setPosts]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[postUploading,setPostUploading]=useState(false),[postCaption,setPostCaption]=useState(""),[postDestination,setPostDestination]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{Promise.all([getProfile(),apiFetch("/profile/posts")]).then(([data,p])=>{setProfile(data);setForm(data);setPosts(p.posts||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const setField=(name,value)=>setForm(c=>({...c,[name]:value}));
 async function logout(){await signOut();navigate("/login",{replace:true});}
 async function handlePhoto(e){const file=e.target.files?.[0];if(!file||!user)return;setError("");setMessage("");setUploading(true);try{const url=await uploadProfilePhoto(file,user.id);const updated=await updateProfile({avatar_url:url});setProfile(updated);setForm(updated);setMessage("Profile photo updated.");}catch(err){setError(err.message)}finally{setUploading(false);e.target.value=""}}
 async function handleBackground(e){const file=e.target.files?.[0];if(!file||!user)return;setError("");setMessage("");setUploading(true);try{const url=await uploadProfileImage(file,user.id,"background");const updated=await updateProfile({background_url:url});setProfile(updated);setForm(updated);setMessage("Profile background updated.");}catch(err){setError(err.message)}finally{setUploading(false);e.target.value=""}}
 async function handlePost(e){const file=e.target.files?.[0];if(!file||!user||!supabase)return;setError("");setMessage("");setPostUploading(true);try{if(!file.type.startsWith("image/"))throw new Error("Please choose an image file.");if(file.size>8*1024*1024)throw new Error("Travel photos must be 8 MB or smaller.");const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=user.id+"/"+crypto.randomUUID()+"."+ext;const {error:up}=await supabase.storage.from("travel-posts").upload(path,file,{contentType:file.type,cacheControl:"3600",upsert:false});if(up)throw new Error(up.message);const {data:url}=supabase.storage.from("travel-posts").getPublicUrl(path);const created=await apiFetch("/profile/posts",{method:"POST",body:JSON.stringify({image_url:url.publicUrl,caption:postCaption,destination:postDestination})});setPosts(x=>[created.post,...x]);setPostCaption("");setPostDestination("");setMessage("Travel post added.");}catch(err){setError(err.message)}finally{setPostUploading(false);e.target.value=""}}
 async function deletePost(id){try{await apiFetch("/profile/posts/"+id,{method:"DELETE"});setPosts(x=>x.filter(p=>p.id!==id));}catch(err){setError(err.message)}}
 async function handleSave(e){e.preventDefault();setError("");setMessage("");setSaving(true);try{const updated=await updateProfile({display_name:form.display_name,bio:form.bio,home_city:form.home_city,travel_style:form.travel_style,budget_min:form.budget_min===""?null:Number(form.budget_min),budget_max:form.budget_max===""?null:Number(form.budget_max),currency:form.currency,interests:form.interests||[],activities:form.activities||[],preferred_destinations:form.preferred_destinations||[],is_discoverable:Boolean(form.is_discoverable)});setProfile(updated);setForm(updated);setMessage("Profile saved successfully.")}catch(err){setError(err.message)}finally{setSaving(false)}}
 if(loading)return <div className="content-wrap"><div className="empty-state-card">Loading your profile…</div></div>;
 if(error&&!profile)return <div className="content-wrap"><div className="empty-state-card error-text">{error}</div></div>;
 const initials=(form.display_name||user?.email||"T").slice(0,1).toUpperCase();
 return <div className="content-wrap">
  <div className="page-heading"><div><p className="eyebrow">YOUR TRAVEL IDENTITY</p><h1>Profile & preferences</h1><p>Keep your identity photo separate from optional travel posts. Posts help other travellers see that your profile represents a real traveller.</p></div><div className="profile-heading-actions"><button type="button" className="profile-logout-button" onClick={logout}>↪ Logout</button><Link className="button button-light" to="/dashboard">← Dashboard</Link></div></div>
  {message&&<div className="success-banner">{message}</div>}{error&&<div className="form-error">{error}</div>}
  <form className="profile-grid" onSubmit={handleSave}>
   <section className="profile-card profile-cover-card"><div className="cover-image" style={form.background_url?{backgroundImage:`url("${form.background_url}")`}:undefined}><div className="cover-gradient"></div><div className="travel-mate-cover-brand" aria-label="Travel Mate"><span className="travel-mate-logo" aria-hidden="true"><svg viewBox="0 0 64 64"><path d="M32 4C18.7 4 8 14.7 8 28c0 17.1 24 32 24 32s24-14.9 24-32C56 14.7 45.3 4 32 4Z" fill="url(#tmLogoGradient)"/><path d="M18 37 27 27l7 7 6-8 9 11H18Z" fill="#fff" opacity=".96"/><path d="M39 18c6 1 9 4 11 9-5-2-9-2-13 0 1-3 1-6 2-9Z" fill="#fff"/><circle cx="31" cy="28" r="2.8" fill="#fff"/><defs><linearGradient id="tmLogoGradient" x1="10" y1="8" x2="54" y2="55" gradientUnits="userSpaceOnUse"><stop stop-color="#1677d2"/><stop offset=".55" stop-color="#13a78b"/><stop offset="1" stop-color="#f2a623"/></linearGradient></defs></svg></span><span>Travel <b>Mate</b></span></div><button type="button" className="cover-edit-button" aria-label="Change background photo" title="Change background photo" onClick={()=>backgroundFileRef.current?.click()}>✎</button><input ref={backgroundFileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={handleBackground}/></div><div className="profile-head"><div className="avatar-wrap"><div className="large-avatar">{form.avatar_url?<img src={form.avatar_url} alt="Profile"/>:initials}</div><button type="button" className="camera-button" aria-label="Change profile photo" title="Change profile photo" onClick={()=>fileRef.current?.click()}>✎</button><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={handlePhoto}/></div><div className="profile-title"><h2>{form.display_name||"Your name"}</h2><p>{form.home_city||"Add your city"} · Solo Traveller</p><span className="profile-status">● {uploading?"Uploading profile photo…":"Dedicated profile photo"}</span></div><button type="button" className="button button-light photo-action" onClick={()=>fileRef.current?.click()}>{uploading?"Uploading…":"Change profile photo"}</button></div></section>
   <section className="profile-card"><div className="card-heading"><div><span className="section-kicker">01</span><h2>Basic information</h2></div><span className="muted">Visible on your profile</span></div><div className="form-grid"><label>Full name<input value={form.display_name||""} onChange={e=>setField("display_name",e.target.value)} placeholder="Your name" maxLength={80}/></label><label>Home city<input value={form.home_city||""} onChange={e=>setField("home_city",e.target.value)} placeholder="e.g. Bengaluru" maxLength={100}/></label><label className="full">Bio<textarea value={form.bio||""} onChange={e=>setField("bio",e.target.value)} placeholder="Tell travellers a little about you, your pace and what you enjoy." maxLength={500} rows={4}/><small>{(form.bio||"").length}/500</small></label></div></section>
   <section className="profile-card"><div className="card-heading"><div><span className="section-kicker">02</span><h2>Travel preferences</h2></div><span className="muted">Used for matching</span></div><div className="form-grid"><label>Travel style<select value={form.travel_style||""} onChange={e=>setField("travel_style",e.target.value)}><option value="">Select your style</option>{travelStyles.map(x=><option key={x}>{x}</option>)}</select></label><label>Currency<select value={form.currency||"INR"} onChange={e=>setField("currency",e.target.value)}><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option></select></label><label>Minimum budget<input type="number" min="0" value={form.budget_min??""} onChange={e=>setField("budget_min",e.target.value)}/></label><label>Maximum budget<input type="number" min="0" value={form.budget_max??""} onChange={e=>setField("budget_max",e.target.value)}/></label><label className="full">Preferred destinations<input value={(form.preferred_destinations||[]).join(", ")} onChange={e=>setField("preferred_destinations",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))} placeholder="Goa, Kerala, Manali"/></label></div></section>
   <section className="profile-card"><div className="card-heading"><div><span className="section-kicker">03</span><h2>Interests & activities</h2></div><span className="muted">Used for matching</span></div><div className="choice-section"><strong>Interests</strong><div className="choice-row">{interestOptions.map(x=><button type="button" key={x} className={form.interests?.includes(x)?"choice selected":"choice"} onClick={()=>setField("interests",toggleItem(form.interests||[],x))}>{x}</button>)}</div></div><div className="choice-section"><strong>Activities</strong><div className="choice-row">{activityOptions.map(x=><button type="button" key={x} className={form.activities?.includes(x)?"choice selected":"choice"} onClick={()=>setField("activities",toggleItem(form.activities||[],x))}>{x}</button>)}</div></div></section>
   <section className="profile-card profile-travel-gallery"><div className="card-heading"><div><span className="section-kicker">04</span><h2>Recent Trips & Travel Photos</h2></div><span className="muted">Show your travel experiences</span></div><div className="travel-gallery-toolbar"><div><strong>Travel memories</strong><small>Upload photos from recent trips. These can be viewed on your public traveller profile.</small></div><button type="button" className="button button-light" onClick={()=>postFileRef.current?.click()} disabled={postUploading}>{postUploading?"Uploading…":"+ Add Photo"}</button><input ref={postFileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={handlePost}/></div>{posts.length?<div className="travel-photo-grid">{posts.map(post=><article className="travel-photo-card" key={post.id}><img src={post.image_url} alt={post.destination||"Travel photo"}/><div className="travel-photo-overlay"><div><strong>{post.destination||"Recent trip"}</strong>{post.caption&&<span>{post.caption}</span>}</div><button type="button" aria-label="Delete travel photo" title="Delete travel photo" onClick={()=>deletePost(post.id)}>×</button></div></article>)}</div>:<div className="travel-photo-empty"><span>📷</span><div><strong>No travel photos yet</strong><small>Add a photo from a recent trip to make your traveller profile more personal.</small></div></div>}</section>
   <section className="profile-card"><div className="card-heading"><div><span className="section-kicker">05</span><h2>Discoverability</h2></div></div><label className="switch-row"><input type="checkbox" checked={Boolean(form.is_discoverable)} onChange={e=>setField("is_discoverable",e.target.checked)}/><span><strong>Show my profile to other travellers</strong><small>Turn this off when you don't want your profile or travel posts in discovery.</small></span></label><div className="actions"><button className="button" disabled={saving}>{saving?"Saving…":"Save profile"}</button></div></section>
  </form>
 </div>
}