import { useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { getProfile, updateProfile, uploadProfilePhoto } from "../lib/profile";

const travelStyles=["Backpacking","Relaxed","Adventure","Luxury","Budget-friendly","Road trip","Nature & outdoors"];
const interestOptions=["Mountains","Beaches","Food","Photography","Culture","Nature","History","Nightlife","Wildlife","Road trips"];
const activityOptions=["Trekking","Hiking","Camping","Sightseeing","Scuba diving","Cycling","Local food","Photography"];

function toggleItem(list,item){return list.includes(item)?list.filter(x=>x!==item):[...list,item]}

export default function Profile(){
 const {user}=useAuth(); const fileRef=useRef(null);
 const [profile,setProfile]=useState(null),[form,setForm]=useState({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{getProfile().then(data=>{setProfile(data);setForm(data)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const setField=(name,value)=>setForm(c=>({...c,[name]:value}));
 async function handlePhoto(e){const file=e.target.files?.[0];if(!file||!user)return;setError("");setMessage("");setUploading(true);try{const url=await uploadProfilePhoto(file,user.id);const updated=await updateProfile({avatar_url:url});setProfile(updated);setForm(updated);setMessage("Profile photo updated.")}catch(err){setError(err.message)}finally{setUploading(false);e.target.value=""}}
 async function handleSave(e){e.preventDefault();setError("");setMessage("");setSaving(true);try{const updated=await updateProfile({display_name:form.display_name,bio:form.bio,home_city:form.home_city,travel_style:form.travel_style,budget_min:form.budget_min===""?null:Number(form.budget_min),budget_max:form.budget_max===""?null:Number(form.budget_max),currency:form.currency,interests:form.interests||[],activities:form.activities||[],preferred_destinations:form.preferred_destinations||[],is_discoverable:Boolean(form.is_discoverable)});setProfile(updated);setForm(updated);setMessage("Profile saved successfully.")}catch(err){setError(err.message)}finally{setSaving(false)}}
 if(loading)return <div className="content-wrap"><div className="empty-state-card">Loading your profile…</div></div>;
 if(error&&!profile)return <div className="content-wrap"><div className="empty-state-card error-text">{error}</div></div>;
 const initials=(form.display_name||user?.email||"T").slice(0,1).toUpperCase();
 return <div className="content-wrap">
  <div className="page-heading"><div><p className="eyebrow">YOUR TRAVEL IDENTITY</p><h1>Profile & preferences</h1><p>Build a profile that tells compatible travellers who you are and how you like to travel.</p></div><Link className="button button-light" to="/dashboard">← Dashboard</Link></div>
  <form className="profile-grid" onSubmit={handleSave}>
   <section className="profile-card profile-cover-card"><div className="cover-image"><div className="cover-gradient"></div></div><div className="profile-head"><div className="avatar-wrap"><div className="large-avatar">{form.avatar_url?<img src={form.avatar_url} alt="Profile"/>:initials}</div><button type="button" className="camera-button" onClick={()=>fileRef.current?.click()}>⌁</button><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={handlePhoto}/></div><div className="profile-title"><h2>{form.display_name||"Your name"}</h2><p>{form.home_city||"Add your city"} · Solo Traveller</p><span className="profile-status">● {uploading?"Uploading photo…":"Profile photo visible on your profile"}</span></div><button type="button" className="button button-light photo-action" onClick={()=>fileRef.current?.click()}>{uploading?"Uploading…":"Upload recent photo"}</button></div></section>
   <section className="profile-card"><div className="card-heading"><div><span className="section-kicker">01</span><h2>Basic information</h2></div><span className="muted">Visible on your profile</span></div><div className="form-grid"><label>Full name<input value={form.display_name||""} onChange={e=>setField("display_name",e.target.value)} placeholder="Your name" maxLength={80}/></label><label>Home city<input value={form.home_city||""} onChange={e=>setField("home_city",e.target.value)} placeholder="e.g. Bengaluru" maxLength={100}/></label><label className="full">Bio<textarea value={form.bio||""} onChange={e=>setField("bio",e.target.value)} placeholder="Tell travellers a little about you, your pace and what you enjoy." maxLength={500} rows={4}/><small>{(form.bio||"").length}/500</small></label></div></section>
   <section className="profile-card"><div className="card-heading"><div><span className="section-kicker">02</span><h2>Travel preferences</h2></div><span className="muted">Used for matching</span></div><div className="form-grid"><label>Travel style<select value={form.travel_style||""} onChange={e=>setField("travel_style",e.target.value)}><option value="">Select your style</option>{travelStyles.map(x=><option key={x}>{x}</option>)}</select></label><label>Currency<select value={form.currency||"INR"} onChange={e=>setField("currency",e.target.value)}><option>INR</option><option>USD</option><option>EUR</option><option>GBP</option></select></label><label>Budget minimum<input type="number" min="0" value={form.budget_min??""} onChange={e=>setField("budget_min",e.target.value)} placeholder="₹ 0"/></label><label>Budget maximum<input type="number" min="0" value={form.budget_max??""} onChange={e=>setField("budget_max",e.target.value)} placeholder="₹ 50,000"/></label><label className="full">Preferred destinations<input value={(form.preferred_destinations||[]).join(", ")} onChange={e=>setField("preferred_destinations",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))} placeholder="Goa, Manali, Bali"/><small>Separate destinations with commas.</small></label></div></section>
   <section className="profile-card"><div className="card-heading"><div><span className="section-kicker">03</span><h2>Interests</h2></div><span className="muted">Choose what you enjoy</span></div><div className="choice-grid">{interestOptions.map(item=><button type="button" className={form.interests?.includes(item)?"choice selected":"choice"} key={item} onClick={()=>setField("interests",toggleItem(form.interests||[],item))}>{form.interests?.includes(item)?"✓ ":""}{item}</button>)}</div></section>
   <section className="profile-card"><div className="card-heading"><div><span className="section-kicker">04</span><h2>Activities</h2></div><span className="muted">What would you do together?</span></div><div className="choice-grid">{activityOptions.map(item=><button type="button" className={form.activities?.includes(item)?"choice selected":"choice"} key={item} onClick={()=>setField("activities",toggleItem(form.activities||[],item))}>{form.activities?.includes(item)?"✓ ":""}{item}</button>)}</div></section>
   <section className="profile-card privacy-card"><div><span className="section-kicker">05</span><h2>Discoverability</h2><p>Allow your profile to appear in traveller discovery and matching.</p></div><label className="switch-row"><input type="checkbox" checked={Boolean(form.is_discoverable)} onChange={e=>setField("is_discoverable",e.target.checked)}/><span className="switch"></span><span><strong>Make my profile discoverable</strong><small>You can change this anytime.</small></span></label></section>
   {(message||error)&&<div className={error?"form-alert error":"form-alert"}>{error||message}</div>}
   <div className="save-bar"><span>Changes are saved to your secure profile.</span><button className="button" disabled={saving||uploading}>{saving?"Saving…":"Save profile changes"}</button></div>
  </form>
 </div>
}